service: nodeless

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: sa-east-1
  memorySize: 256
  iamRoleStatements:
    Effect: Allow
    Action:
      s3:GetObject
      s3:PutObject
    Resource: 
      "arn:aws:s3:::*"


functions:
  hello:
    handler: handler.hello
    enviroment:
      bucket: serverless
    events:
      s3:
        bucket: serverlesscd
        event: s3:ObjectCreated:*
